
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 31 12:10:24 EDT 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LEFTBRACKET = 9;
  public static final int ASSIGNMENT = 17;
  public static final int PERIOD = 2;
  public static final int RIGHTPAREN = 8;
  public static final int RIGHTBRACKET = 10;
  public static final int INTEGER = 38;
  public static final int INT = 24;
  public static final int PRINTLN = 32;
  public static final int MINUS = 15;
  public static final int LEFTPAREN = 7;
  public static final int STAR = 14;
  public static final int STATIC = 30;
  public static final int SEMICOLON = 4;
  public static final int AND = 11;
  public static final int LESSTHAN = 12;
  public static final int COMMA = 3;
  public static final int CLASS = 19;
  public static final int PLUS = 16;
  public static final int MAIN = 26;
  public static final int IF = 23;
  public static final int EXCLAMATION = 13;
  public static final int THIS = 33;
  public static final int EOF = 0;
  public static final int BOOLEAN = 18;
  public static final int RETURN = 29;
  public static final int TRUE = 34;
  public static final int RIGHTCURLY = 6;
  public static final int NEW = 27;
  public static final int error = 1;
  public static final int VOID = 35;
  public static final int LEFTCURLY = 5;
  public static final int ELSE = 20;
  public static final int WHILE = 36;
  public static final int PUBLIC = 28;
  public static final int EXTENDS = 21;
  public static final int STRING = 31;
  public static final int FALSE = 22;
  public static final int LENGTH = 25;
  public static final int IDENTIFIER = 37;
}

